version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    restart: always
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/mydatabase?authSource=admin
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    environment:
      REACT_APP_API_URL: http://node-backend:5000
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  mongo-data:


networks:
  app-network:
